language: node_js
node_js:
  - "node"
  - "12"
  - "11"
  - "10"
  - "8"

cache:
  directoreis:
    - $HOME/.npm

before_install:
  - npm install --global npm@latest
  - npm --version

install:
  - npm ci

script:
  - npm test
